
export const AuthMessages = {
    OTP_SENT_SUCCESS: 'OTP sent successfully',  
    USER_REGISTERED_SUCCESS: 'User Registered Successfully',
    LOGIN_SUCCESSFUL: 'Login successful',
    INVALID_REGISTRATION_ROUTE:'Invalid registration route',
    EMAIL_ALREADY_REGISTERED: 'Email is already registered',
    USERNAME_ALREADY_TAKEN: 'Username is already taken',
    EMAIL_ALREADY_EXISTS: 'User with this email already exists',
    INVALID_OTP: 'Invalid OTP! Please try again',
    REGISTRATION_FAILED: 'User registration failed',
    INVALID_CREDENTIALS: 'Invalid Credentials',
    USER_NOT_FOUND: "Sorry, we couldn't find the user you're looking for.",
    OTP_NOT_SENT:'Failed to sent OTP.', 
    UNEXPECTED_ERROR: 'An unexpected error occurred',
    FAILED_TO_VERIFY_USER:" Failed to verify user",
    NOT_FOUND: 'Resource not found',
    USER_LOGOUT: 'Logout successfully',
    LOGOUT_FAILED:'Failed to logout',
    TOKEN_AND_OTP_REQUIRED: 'Please enter OTP',
    INVALID_TOKEN: 'Reset link has been expired',
    TOKEN_IS_NOT_VALID:"Invalid token",
    INVALID_REFRESH_TOKEN:'Invalid refresh token ',
    TOKEN_EXPIRED:'Token expired comes ',
    RESET_LINK_EXPIRED: 'Your password reset link has expired. Please request a new one',
    EXPIRED_OR_INVALID_TOKEN: "Refresh token expired or invalid",
    TOKEN_REFRESH_ERROR: "An error occurred while refreshing the token",
    INVALID_LOGIN_ROUTE: "You don't have an account",
    UNDEFINED_ACCESS_AND_REFRESH:'JWT_SECRET or JWT_REFRESH_SECRET is not defined',
    TOKEN_REFRESH_SUCCESSFULL:'Token refreshed successfully',
    USERS_LISTED_SUCCESSFULLY: 'Users listed successfully',
    UPDATED_SUCCESSFULL: 'Updated Successfully',
    USER_BLOCKED:'Your account has been blocked. Try later',
    USER_IS_NOT_APPROVED:'User is not approved',
    NO_TUTOR_FOUND:'Tutors Not Found',
    TUTORS_LISTED_SUCCESSFULLY:'Tutors listed successfully',
    USER_WITH_THIS_EMAIL_NOT_FOUND:"User with this email doesn't exist",
    FAILED_TO_SEND_EMAIL:'Failed to send email ...',
    EMAIL_FUNCTIONALITY_FAILED:'Nodemailer failed',
    RESET_LINK_SENT:'Password reset link sent to email',
    PASSWORD_RESET_FAILED:'Password reset failed',
    PASSOWRD_RESET_SUCCESSFULL:'Password reset successfull',
    VALID_TOKEN:'Valid token',
    INVALID_ROLE_AND_EMAIL:"Email doesn't exists",
    INVALID_ROLE:"You're not an autherized user",
    FILE_DOESNT_EXISTS_OR_INVALID:'File does not exits',
    UPLOAD_FAILED:'Could not update user image',
    IMAGE_FILE_DOESNOT_EXISTS:"No image file provided",
    PROFILE_UPLOADED_SUCCESSFULLY:"Profile uploaded successfully",
    UNATHERIZED_USER:"token does not exits",
    FAILED_TO_CREATE_PROBLEM:'Failed to add new problem',
    PROBLEM_CREATED_SUCCESSFULLY:'Problem created successfully',
    PROBLEM_LISTED_SUCCESSFULLY:'Problem listed successfully',
    FAILED_TO_LIST_PROBLEMS:'Failed to list problems',
    PROBLEM_NOT_FOUND:"Sorry, we couldn't find the problem you're looking for.",
    PROBLEM_STATUS_UPDATED_SUCCESSFULLY:'Problem status updated successfully',
    ERROR_BLACKLISTING_TOKEN:'Error blacklisting token',
    ERROR_CHECKING_BLACKLISTING_TOKEN:'Error checking blacklisted token',
    FAILED_TO_CREATE_COURSE:'Error creating course',
    COURSE_CREATED_SUCCESSFULLY:"Course Created Successfully",
    ROLEID_IS_REQUIRED:'Role ID is required',
    INVALID_CURRENT_PASSWORD: "Current password is incorrect",
    PASSWORD_UPDATE_FAILED: "Failed to update password",
    MISSING_REQUIRED_FIELDS: "Missing required fields while uploading course",
    MISSING_COVER_IMAGE:'Missing Cover Image',
    COURSE_NOT_FOUND:"Sorry, we couldn't find the course you're looking for.",
    COURSE_LISTED_SUCCESSFULLY:'Course listed successfully',
    COURSE_STATUS_UPDATED_SUCCESSFULLY:'Course status updated successfully',
    COURSE_AND_USER_ID_MISSING: 'Course and user Id is required',
    ERROR_FETECHING_CART_BY_USER: 'Error fetching cart by userId',
    COURSE_EXISTS_IN_CART:"course exists in the cart",
    CART_ADDED:'Course added to cart successfully',
    ERROR_FETECHING_WISHLIST_BY_USER: 'Error fetching wishlist by userId',
    COURSE_EXISTS_IN_WISHLIST:"Course already listed",
    WISHLIST_ADDED: 'Course listed has a favourite',
    PAGE_NOT_FOUND:'Page Not Found',
    CART_IS_EMPTY: 'No items found in the cart',
    CHECKOUT_IS_EMPTY:"Payment already proceeded, check transaction history",
    CART_LISTED_SUCCESSFULLY: 'Cart listed successfully',
    INVALID_USER_ID: 'Invalid user Id',
    USERID_ITEMID_MISSING:'User ID and Item ID are required',
    CART_NOT_FOUND:'Cart not found',
    FAILED_TO_UPDATE_CART: 'Failed to remove from the cart',
    ITEM_REMOVED_SUCCESSFULLY:"Item removed successfully",
    WISHLIST_IS_EMPTY:"No items found",
    WISHLIST_LISTED_SUCCESSFULLY:"wishlist listed successfully",
    WISHLIST_NOT_FOUND:"wishlist is not found",
    WISHLIST_UPDATED_SUCCESSFULLY:"wishlist updated successfully",
    FAILED_TO_UPDATE_WISHLIST:"Failed to updated wishlist",
    STRIEP_SESSION_CREATED_SUCESSFULLY:"Strip sesssion created successfully",
    ORDER_NOT_FOUND: 'Order not found',
    PAYMENT_VERIFICATION_FAILED: 'Payment Verification failed',
    PAYMENET_VERIFIED_SUCCESSFULLY: 'Payment verified successfully',
    PAYMENT_NOT_COMPLETED: 'Payment not completed',
    ORDER_ID_NOT_FOUND_IN_SESSION:'Order ID not found in session metadata',
    PAYMENT_FAILED: 'Payment failed',
    ORDER_LISTED_SUCESSFULLY: 'Order listed successfully',
    FAILED_TO_FETCH_ORDER: 'Failed to fetch order data',
    UNAUTHORIZED_ORDER: 'Unauthorized order',
    YOUR_WALLET_ACTIVATED_SUCCESSFULLY:'Your wallet has been successfully activated.',
    WALLET_INFO_NOT_FOUND: 'User wallet not found',
    INVALID_AMOUNT: 'Transaction amount should be greater than 100',
    WALLET_NOT_FOUND: 'Wallet not found',
    WALLET_ACTIVATION_PENDING: "Please activate your wallet",
    TRANSACTION_NOT_FOUND: 'Wallet transaction id not found',
    AMOUNT_NOT_FOUND:'Wallet top up amount not found',
    WALLET_PAYMENT_FAILED: 'Payment failed',
    WALLET_UPDATE_FAILED: 'Failed to updated wallet',
    ORDER_PLACED_SUCCESSFULLY: 'Order successfully completed',
    INSUFFICIENT_BALANCE: 'Insufficient wallet balance. Consider using differnt platform',
    FAILED_TO_UPDATE_COURSE_REVIEW: 'Failed to update course review',
    NO_REVIEWS_FOUND: 'No review found for this course',
    REVIEW_ADDED_SUCCESSFULLY: 'Review added successfully',
    REVEIW_LISTED_SUCCESSFULLY:'Review listed successfully',
    NOT_PURCHASED: 'Product Not Purchased',
    MISSING_REQUIRED_FIELDS_CODE: 'fields are missing from req',
    MISSING_TEST_CASES: 'No test cases defined for this problem',
    FAILED_TO_RUN_CODE: 'Failed to run code',
    FAILED_CODE_SUBMISSION: 'Code submission failed',
    CODE_SUBMITTED_SUCCESFULLY: 'Code submitted successfully',
    FEEDBACK_ADDED_SUCCESSFULLY: 'Feedback added successfully',
    NO_FEEDBACK_MESSAGE_FOUND: 'Message not found',
    FEEDBACK_LESTED_SUCCESSFULLY: 'Feedbacks are listed successfully',
    COURSE_ALREDAY_PURCHASED: "It looks like you've already purchased this course. Please check your dashboard to access the course.",
    FILE_SORTAGE: 'Not enough files provided for all videos',
    FAILED_TO_UPDATE_PROBLEM_REVIEW:'Failed to update problem review',
    UNSUBMITTED_CODE: " Submit the code before adding review",
    FAILED_UPDATE_USER_PROGRESS: 'Failed to update the user progress',
    FETCH_PROBLEM_COUNTS:'Total number of problems fetched successfully',
    NO_MESSAGES_FOUND: 'No messages found',
    MESSAGE_LISTED_SUCCESFULLY: 'Message listed successfully',
    USERS_NOT_FOUND:'neither tutor nor user is found',
    MESSAGE_SENT_SUCCESSFULLY:' Message sent successfully',
    FAILED_TO_FETCH_MESSAGES: 'Failed to fetch previous messages',
    FAILED_TO_UPDATE: 'Failed to update',
    PROBLEMS_UPDATED_SUCCESSFULLY: 'Problem updated successfully',
    ERROR_UPLOADING_FILES_TO_S3: 'Error uploading files to S3',
    FETCHED_DASHBOARD_STATS_SUCCESSFULLY: 'Fetched dashboard stat successfully',
    ORDER_ALREADY_IN_PROGRESS: 'Order already in progress..',
    ORDER_CONFLICT: 'Course already purchased',
    FAILED_TO_SAVE_CALL_HISTORY: 'Failed to save call history',
    FAILED_TO_UPDATE_CALL_HISTORY: 'Failed to updated call history',
    FAILED_TO_FETCH_CALL_HISTORY:'Failed to fetch call history',
    CHAPTER_NOT_FOUND:'Chapter does not exists in a course',
    VIDEO_NOT_FOUND:'Video does not exists in a course',
    COURSE_PROGRESS_UPDATED: 'Course progress updated successfully'
};      